### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by TawfikYasser** [salahineo/resources#1]
Hi

I want to use the project, But i am not a web developer and it is a huge process to install XAMPP and the rest of tasks to work on the bookmark manager, as a normal user it is hard, What about make it as a chrome extension.

Thanks

**Comment by salahineo** [comment]
Hi Tawfik, I hope you have a good day.

I agreed with you about this, it is really difficult for normal users to finish the installation process, But I'm not familiar with browser extension development. So I will think about making this application available for desktop, which will make it easier to use & install.

Thank you for your suggestion, and wait for the good news soon.

**Comment by salahineo** [comment]
Hi Tawfik, I hope you have a good day.

I agreed with you about this, it is really difficult for normal users to finish the installation process, But I'm not familiar with browser extension development. 
I even decide to compile this web application into a desktop application by making a portable local server and embedded browser in one windows application, But I found a problem of opening bookmark links because it opened in the desktop application itself, not in the OS browser.
So as a final solution, I decided to make a tutorial video to explain how to run this project on your localhost

Thank you for your suggestion, and wait for the video link soon.

**Comment by TawfikYasser** [comment]
Okay, @salahineo , Thanks for your interest, I think you can share the topic on LinkedIn to see suggestions, May be find someone help you.

**Comment by salahineo** [comment]
Ok, Thanks for your suggestions 👏

**Comment by salahineo** [comment]
Here is a [video tutorial](https://drive.google.com/drive/folders/1n45WgdyVsx9ZstCXPuMZG_sL-QbpW0Gg), to show you how to install XAMPP, and this project step by step.
I'm not an expert in recording videos, So the video quality maybe not good enough.
If you face any problem, let me know and try to help you.

Finally I wait for your opinion about this project 😊

**Comment by TawfikYasser** [comment]
Thanks @salahineo  for your time it is really good, I will try it and get back to you. :)

**Comment by salahineo** [comment]
Thanks, @TawfikYasser for your interest. I'm waiting for your opinion 😊

**Comment by salahineo** [comment]
Thanks, @TawfikYasser for your interest.
